window:
  # Window position (changes require restart)
  position:
    x: 0
    y: 0

  # Window padding (changes require restart)
  padding:
    x: 2
    y: 2

  # Allow terminal applications to change Alacritty's window title.
  dynamic_title: false

scrolling:
  # Maximum number of lines in the scrollback buffer.
  history: 10000

  # Scrolling distance multiplier.
  multiplier: 5

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: JetBrains Mono
    style: Regular

  # Bold font face
  bold:
    family: JetBrains Mono
    style: Bold

  # Italic font face
  italic:
    family: JetBrains Mono
    style: Italic

  # Point size
  size: 13.5

  # Offset is the extra space around each character.
  offset:
    x: 0
    y: 0

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

# Colors
colors:
  # Default colors
  primary:
    background:        '#080808'
    foreground:        '#b2b2b2'
    bright_foreground: '#eeeeee'

  # Cursor colors
  cursor:
    text:   '#080808'
    cursor: '#9e9e9e'

  # Vi mode cursor colors
  vi_mode_cursor:
    text:   '#080808'
    cursor: '#e3c78a'

  # Selection colors
  selection:
    text:       '#080808'
    background: '#b2ceee'

  # Search colors
  search:
    matches:
      background: '#e3c78a'
      foreground: '#080808'
    bar:
      background: '#e3c78a'
      foreground: '#080808'

  # Normal colors
  normal:
    black:   '#323437'
    red:     '#ff5454'
    green:   '#8cc85f'
    yellow:  '#e3c78a'
    blue:    '#80a0ff'
    magenta: '#d183e8'
    cyan:    '#79dac8'
    white:   '#a1aab8'

  # Bright colors
  bright:
    black:   '#7c8f8f'
    red:     '#ff5189'
    green:   '#36c692'
    yellow:  '#bfbf97'
    blue:    '#74b2ff'
    magenta: '#ae81ff'
    cyan:    '#85dc85'
    white:   '#e2637f'

selection:
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

# Live config reload (changes require restart)
live_config_reload: true

# Bell
bell:
  command: None

mouse:
  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true

# # Key bindings
key_bindings:
  - { key: C,        mods: Command,   action: Copy                   }
  - { key: V,        mods: Command,   action: Paste                  }
  - { key: Equals,   mods: Command,   action: IncreaseFontSize       }
  - { key: Minus,    mods: Command,   action: DecreaseFontSize       }
  - { key: Q,        mods: Control,   chars: "\x11"                  }
  - { key: A,        mods: Alt,       chars: "\x1ba"                 }
