window:
  # Window position (changes require restart)
  position:
    x: 0
    y: 0

  # Window padding (changes require restart)
  padding:
    x: 2
    y: 2

  # Allow terminal applications to change Alacritty's window title.
  dynamic_title: false

scrolling:
  # Maximum number of lines in the scrollback buffer.
  history: 10000

  # Scrolling distance multiplier.
  multiplier: 5

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: JetBrainsMonoNL Nerd Font
    style: Regular

  # Bold font face
  bold:
    family: JetBrainsMonoNL Nerd Font
    style: Bold

  # Italic font face
  italic:
    family: JetBrainsMonoNL Nerd Font
    style: Italic

  # Point size
  size: 13.5

  # Offset is the extra space around each character.
  offset:
    x: 0
    y: 0

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

# Colors
colors:
  # Default colors
  primary:
    background: '0x24283b'
    foreground: '0xc0caf5'

  # Normal colors
  normal:
    black:   '0x1D202F'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan:    '0x7dcfff'
    white:   '0xa9b1d6'

  # Bright colors
  bright:
    black:   '0x414868'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan:    '0x7dcfff'
    white:   '0xc0caf5'

  indexed_colors:
    - { index: 16, color: '0xff9e64' }
    - { index: 17, color: '0xdb4b4b' }

selection:
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

# Live config reload (changes require restart)
live_config_reload: true

# Bell
bell:
  command: None

mouse:
  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: false

# # Key bindings
key_bindings:
  - { key: C,        mods: Command,   action: Copy                   }
  - { key: V,        mods: Command,   action: Paste                  }
  - { key: Equals,   mods: Command,   action: IncreaseFontSize       }
  - { key: Minus,    mods: Command,   action: DecreaseFontSize       }
  - { key: Q,        mods: Control,   chars: "\x11"                  }
  - { key: A,        mods: Alt,       chars: "\x1ba"                 }
