alias ..='cd ..'
alias be='bundle exec'
alias c='clear'
alias dbm='bundle exec rails db:migrate'
alias dbmt='bundle exec rails db:migrate RAILS_ENV=test'
alias dbs='bundle exec rails db:migrate:status'
alias dbst='bundle exec rails db:migrate:status RAILS_ENV=test'
alias dlog='tail -f log/development.log'
alias gb='fzf_git_branch | xargs git checkout'
alias gcurrent="git rev-parse --abbrev-ref HEAD"
alias glS='fzf_git_log_pickaxe'
alias gll='fzf_git_log'
alias gv='gh pr view -w'
alias gva='gh pr list -A pborak -w'
alias gpr='fzf_github_prs'
alias l='ls -laFhG'
alias ls='ls -G'
alias rc='bundle exec rails c'
alias tlog='tail -f log/test.log'
alias vi='nvim'
alias vim="nvim"
alias ssh='TERM="xterm-256color" ssh'
