alias ..='cd ..'
alias be='bundle exec'
alias bl='./base local-proxy start'
alias bs='./base start @base-core/app'
alias c='clear'
alias dbm='be rails db:migrate'
alias dbmt='be rails db:migrate RAILS_ENV=test'
alias dbs='be rails db:migrate:status'
alias dbst='be rails db:migrate:status RAILS_ENV=test'
alias dc='docker-compose'
alias dcb='docker-compose exec -it backend'
alias dlog='tail -f log/development.log'
alias ga='fzf_git_add'
alias gb='fzf_git_branch | xargs git checkout'
alias gcurrent="git rev-parse --abbrev-ref HEAD"
alias glS='fzf_git_log_pickaxe'
alias gll='fzf_git_log'
alias gv='gh pr view -w'
alias gva='gh pr list -a pborak -w'
alias l='ls -laFhG'
alias ls='ls -G'
alias rc='be rails c'
alias rs='be rails s'
alias tf='./base test'
alias tlog='tail -f log/test.log'
alias vi='nvim'
alias vim="nvim"
alias ssh='TERM="xterm-256color" ssh'
