alias ..='cd ..'
alias be='bundle exec'
alias c='clear'
alias dbm='be rails db:migrate'
alias dbmt='be rails db:migrate RAILS_ENV=test'
alias dbs='be rails db:migrate:status'
alias dbst='be rails db:migrate:status RAILS_ENV=test'
alias dlog='tail -f log/development.log'
alias gv='gh pr view -w'
alias l='ls -laFhG'
alias ls='ls -G'
alias prc='gh pr create -w -a pBorak -r zendesk/sell-growth'
alias rc='be rails c'
alias rg='rg --smart-case'
alias rs='be rails s'
alias tf='./base test --files'
alias tlog='tail -f log/test.log'
alias vi='nvim'
alias vrc='nvim ~/code/dotfiles/.vimrc'
