bindkey "^a" beginning-of-line
bindkey "^e" end-of-line
bindkey "^f" forward-word
bindkey "^b" backward-word
bindkey "^p" history-search-backward
bindkey "^n" history-search-forward
bindkey "^u" backward-kill-line
bindkey "^y" autosuggest-accept
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
