gui:
  mouseEvents: true
  nerdFontsVersion: "3"
  language: auto
  timeFormat: 02 Jan 06 15:04 MST
  theme:
    activeBorderColor:
      - "#ff966c"
      - bold
    inactiveBorderColor:
      - "#589ed7"
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - "#2f334d"
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  editPreset: "nvim"
services:
  gitlab.housecalldev.com: gitlab:gitlab.housecalldev.com
